eventProcessorWorkers: 10
inMemoryStorageAdaptor: "org.apache.airavata.datalake.orchestrator.db.inmemory.DefaultInMemoryStore"
messageFilter:
  resourceType: "FILE"
  eventType: "CREATE,MODIFY "
  resourceNameExclusions: "swp$"
outboundEventProcessor:
  pollingInterval: 5
  workflowEngineHost: "localhost"
  workflowPort: 6565
  drmsHost: "localhost"
  drmsPort: 7070
consumer:
  brokerURL: "149.165.157.235:9092"
  consumerGroup: "DataOrchestratorGroup"
  topic: "data-orchestrator-file-events"
  maxPollRecordsConfig: 10