pollingInterval: 60
dataResourceManagementService:
  dbURI: "bolt://149.165.156.173:7687"
  dbUser: "neo4j"
  dbPassword: "blastcovid19"
custos:
  host: "custos.scigap.org"
  port: 31499
  custosId: "custos-2zuomcugra3ebgsqtzmf-10000514"
  custosSec: "mupUhF4JL0S3IFHBjfhiTfLJS1NgSWfvkCj3l6c7"
  tenantsToBeSynced:
    -  "custos-cmcdclbywlxmc2ktzv0d-10000702"
