pollingInterval: 60
dataResourceManagementService:
  dbURI: "bolt://149.165.156.173:7687"
  dbUser: "neo4j"
  dbPassword: "blastcovid19"
custos:
  host: "custos.scigap.org"
  port: 31499
  custosId: "custos-whedmgamitu357p4wuke-10002708"
  custosSec: "mrMdl86Ia1H94cikW7CvHoh7L0ASNXQVt2aRzSIj"
  custosBrokerURL: "149.165.156.200:9092"
  consumerGroup: "custosEventsGroup"
  maxPollRecordsConfig: 10
  topics:
    - "10002708-754b89b5-3a57-496c-aa34-8e2b4916fbc"
  tenantsToBeSynced:
    - "custos-whedmgamitu357p4wuke-10002708"
