pollingInterval: 60
dataResourceManagementService:
  dbURI: "bolt://149.165.156.173:7687"
  dbUser: "neo4j"
  dbPassword: "blastcovid19"
custos:
  host: "custos.scigap.org"
  port: 31499
  custosId: "custos-ii8g0cfwsz6ruwezykn9-10002640"
  custosSec: "OxXECszt9dL4lHJQyL444UOU0lKN317D51ez067R"
  custosBrokerURL: "149.165.156.200:9092"
  consumerGroup: "custosEventsGroup"
  maxPollRecordsConfig: 10
  topics:
    - "10002640-561b67b4-fa7d-4368-8643-dcd9d0159c1d"
  tenantsToBeSynced:
    - "custos-ii8g0cfwsz6ruwezykn9-10002640"
