fileServerHost: "apidev.scigap.org"
fileServerPort: 3124
fileServerProtocol: "SFTP"
listeningPath: "/Users/dimuthu/EMC-data"

producer:
  brokerURL: "localhost:9092"
  publisherId: "DataOrchestratorProducer"
  publisherTopic: "quickstart-events"