listeningPath: "/Users/isururanawaka/Documents/texts"
hostName: "beta.iubemcenter.scigap.org"

producer:
  brokerURL: "localhost:9092"
  publisherId: "DataOrchestratorProducer"
  publisherTopic: "quickstart-events"

custos:
  serviceAccountId: ""
  serviceAccountSecret: ""
  tenantId: ""
